[package]
name = "godot-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
scopeguard = "^1.1.0"
gdnative = "^0.11"
parking_lot = "^0.12"
anyhow = "^1.0"
lazy_static = "^1.4"
slab = "^0.4"

[dependencies.wasmtime]
version = "^3.0"
default-features = false
features = [
  "cranelift",
  "wat",
  "parallel-compilation",
]
