[package]
name = "godot-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "^0.9"
parking_lot = "^0.11"
anyhow = "^1.0"
indexmap = "^1.7"
hashbrown = "^0.11"

[dependencies.wasmtime]
version = "^0.32"
default-features = false
features = [
  "wat",
  "parallel-compilation",
  "cranelift"
]
