[package]
name = "godot-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = "thin"
codegen-units = 1

[dependencies]
scopeguard = "^1.1.0"
gdnative = "^0.11"
parking_lot = "^0.12"
anyhow = "^1.0"
lazy_static = "^1.4"
slab = { version = "^0.4", optional = true }
wasmtime-wasi = { version = "^8.0", optional = true }
wasi-common = { version = "^8.0", optional = true }
async-trait = { version = "^0.1", optional = true }
cfg-if = { version = "^1.0", optional = true }

[dependencies.wasmtime]
version = "^8.0"
default-features = false
features = [
  "cranelift",
  "wat",
  "parallel-compilation",
]

[features]
default = ["epoch-timeout", "memory-limiter", "object-registry", "wasi"]
memory-limiter = []
epoch-timeout = []
object-registry-compat = ["dep:slab"]
object-registry-extern = []
object-registry = ["object-registry-compat", "object-registry-extern"]
more-precise-timer = []
wasi = [
  "dep:wasmtime-wasi",
  "dep:wasi-common",
  "dep:async-trait",
  "dep:cfg-if",
]

[workspace]
members = [
  "example/wasm/*",
]
exclude = [
  "example/wasm/.cargo",
]
