[package]
name = "godot-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
scopeguard = "^1.1.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
parking_lot = "^0.12"
anyhow = "^1.0"
lazy_static = "^1.4"
slab = "^0.4"

[dependencies.wasmtime]
version = "^6.0"
default-features = false
features = [
  "cranelift",
  "wat",
  "parallel-compilation",
]

[features]
default = ["epoch-timeout"]
epoch-timeout = []
object-registry-compat = []
object-registry-extern = []
object-registry = ["object-registry-compat", "object-registry-extern"]
more-precise-timer = []

[workspace]
members = [
  "example/wasm/*",
]
exclude = [
  "example/wasm/.cargo",
]
