[package]
name = "godot-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "^0.10"
parking_lot = "^0.11"
anyhow = "^1.0"
lazy_static = "^1.4"

[dependencies.wasmer]
version = "^2.3"
features = [
  "default-cranelift",
  "default-universal",
]
