[package]
name = "godot-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "^0.11"
parking_lot = "^0.12"
anyhow = "^1.0"
lazy_static = "^1.4"

[dependencies.wasmer]
version = "^3.0"
