[build]
target = "wasm32-unknown-unknown"
rustflags = ["-C", "target-feature=+multivalue,+mutable-globals,+reference-types,+bulk-memory,+sign-ext"]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
debug-assertions = false
overflow-checks = false
