[build]
target = "wasm32-unknown-unknown"
rustflags = ["-C", "target-feature=+bulk-memory,+mutable-globals,+nontrapping-fptoint,+reference-types,+sign-ext"]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
debug-assertions = false
overflow-checks = false
