[package]
name = "host-bindings"
version = "0.1.0"
edition = "2021"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wee_alloc = "0.4.5"
